version: '3'
services:
  app:
    container_name: gobarber_app
    build: .
    environment:
      - MONGO_URI=mongodb://mongo/todo
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3333:3000"
    depends_on:
      - db
    command: yarn dev

  db:
    image: postgres:11
    container_name: gobarber_db
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: gobarber
      POSTGRES_PASSWORD: gobarber
      POSTGRES_DB: jupiter_bank_db